//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "spec_values")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub dim_id: i32,
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::spec_dims::Entity",
        from = "Column::DimId",
        to = "super::spec_dims::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SpecDims,
    #[sea_orm(has_many = "super::variant_values::Entity")]
    VariantValues,
}

impl Related<super::spec_dims::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpecDims.def()
    }
}

impl Related<super::variant_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VariantValues.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
