//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "variant_values")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub variant_id: i32,
    pub value_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product_variants::Entity",
        from = "Column::VariantId",
        to = "super::product_variants::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ProductVariants,
    #[sea_orm(
        belongs_to = "super::spec_values::Entity",
        from = "Column::ValueId",
        to = "super::spec_values::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SpecValues,
}

impl Related<super::product_variants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductVariants.def()
    }
}

impl Related<super::spec_values::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SpecValues.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
